server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 205MB
      max-request-size: 205MB
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  jjwt:
    secretKey: yeojuSecretKeyAT
    expiredDate: 86400000
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:sqlserver://172.16.7.130:1433;databaseName=ZKAccess
    username: sa
    password: Pa$$w0rd2020
  main:
    allow-circular-references: true
  #    namangan database
#    url: jdbc:sqlserver://172.50.7.247:1433;databaseName=ZKAccess
#    username: sa
#    password: Test@123

#    samarqand database
#    url: jdbc:sqlserver://172.30.7.130:1433;databaseName=ZKAccess
#    username: sa
#    password: Test@123

#    url: jdbc:sqlserver://172.16.1.234:1433;databaseName=ZKAccess --ErpKIUT
#    username: sa
#    password: 0806

#    hikari:
#      maximum-pool-size: 200
  #    url: jdbc:sqlserver://localhost:1433;databaseName=TEST_ZKA
  #    username: root
  #    password: root123
  #    url: jdbc:sqlserver://localhost:1433;databaseName=ZKA
  #    username: root
  #    password: root123
  jackson:
    serialization:
      fail-on-empty-beans: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: asadovtohir2002@gmail.com
    password: kmpsrvraanifhapj
    properties:
      nail:
        smtp:
          auth: true
          starttls: true
app:
  sms:
    countPerDay: 3
    username: yodju
    password: oeTT8C
    url: http://91.204.239.44/broker-api
#  authentication:
#    attempts: 3
#    jwtSecret: aUtO2019#BiO@07tAsHkeT04teAmYouthinKbReAk2060yeAr_riGht
#    ## Applicant jwt expiration time: 1 year
#    jwtExpirationInMs: 31536000000
#    ## Backend admin jwt expiration time: 1 year
#    jwtBackendExpirationInMs: 31536000000
#  authentication:
#    attempts: 3
#    jwtSecret: aUtO2019#BiO@07tAsHkeT04teAmYouthinKbReAk2060yeAr_riGht
#    ## Applicant jwt expiration time: 1 year
#    jwtExpirationInMs: 31536000000
#    ## Backend admin jwt expiration time: 1 year
#    jwtBackendExpirationInMs: 31536000000

#server.port=8081
#
##spring.mysql.datasource.url=jdbc:mysql://localhost:3306/yeoju2
##spring.mysql.datasource.username=root
##spring.mysql.datasource.password=root123
##spring.mysql.datasource.driver-class-name=com.mysql.jdbc.Driver
#
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=yeojuZKA
#spring.datasource.username=root
#spring.datasource.password=root123
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#
#spring.jpa.properties.hibernate.globally_quoted_identifiers=true
#
##
##spring.jpa.properties.hibernate.format_sql=true
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2008Dialect
###
##
##
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#
#
#
#
#spring.jpa.generate-ddl=true
#spring.jpa.show-sql=true
#
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=never
#
#spring.jjwt.secretKey=yeojuSecretKeyAT
#spring.jjwt.expiredDate=86400000
#
#spring.data.rest.base-path=/api
#
#spring.jpa.properties.hibernate.enable_lazy_load_on_trans=true
#spring.jackson.serialization.fail-on-empty-beans=false
#
#### File ni max size
#spring.servlet.multipart.max-file-size=10MB
#### So'rovni ni max size
#spring.servlet.multipart.max-request-size=10MB
#
### To customize logging pattern.
##logging.pattern.file="%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
##logging.level.root=warn
##logging.level.org.springframework.web=debug
##logging.level.org.hibernate=error
#
#
#
##spring.datasource.hikari.connection-timeout=40000
##spring.datasource.hikari.minimum-idle=5
##spring.datasource.hikari.maximum-pool-size=50
##spring.datasource.hikari.idle-timeout=300000
##spring.datasource.hikari.max-lifetime=1200000
##spring.datasource.hikari.auto-commit=false
#
##spring.datasource.tomcat.max-active=500
##spring.datasource.tomcat.test-on-borrow=true
##spring.datasource.tomcat.max-wait=10000
#
#spring.datasource.hikari.connectionTimeout=30000
#spring.datasource.hikari.idleTimeout=600000
#spring.datasource.hikari.maxLifetime=1800000
#spring.datasource.type=com.zaxxer.hikari.HikariDataSource
#
#spring.datasource.hikari.minimumIdle=10
#spring.datasource.hikari.maximumPoolSize=20
#spring.datasource.hikari.poolName=SpringBootJPAHikariCP
#spring.datasource.hikari.data-source-properties.cachePrepStmts= true
#spring.datasource.hikari.data-source-properties.prepStmtCacheSize= 250
#spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit= 2048
#spring.datasource.hikari.data-source-properties.useServerPrepStmts= true
#spring.datasource.hikari.data-source-properties.useLocalSessionState= true
#spring.datasource.hikari.data-source-properties.rewriteBatchedStatements= true
#spring.datasource.hikari.data-source-properties.cacheResultSetMetadata= true
#spring.datasource.hikari.data-source-properties.cacheServerConfiguration= true
#spring.datasource.hikari.data-source-properties.elideSetAutoCommits= true
#spring.datasource.hikari.data-source-properties.maintainTimeStats= false
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#
#
#app.sms.countPerDay=3
#app.sms.username=yodju
#app.sms.password=oeTT8C
#app.sms.url=http://91.204.239.44/broker-api